language: go
go_import_path: github.com/platonnetwork/PlatON-Go
sudo: false
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      go: 1.11.x
      script:
        - go test ./...