language: go
go_import_path: github.com/PlatONnetwork/PlatON-Go
# sudo: false
matrix:
  include:
    # This builder compile PlatON at Ubuntu xenial
    - name: ubuntu compile
      os: linux
      dist: xenial
      sudo: required
      go: 1.12.x
      script:
        - chmod u+x ./build/*.sh
        - make all

    # This builder compile PlatON at Windows server 2016
    - name: windows compile
      os: windows
      go: 1.12.x
      addons:
        
      script:
        - chmod u+x ./build/*.sh
        - sh ./build/build_deps.sh
        - go run build/ci.go install

    # This builder run the code scans uses gometalinter
    - name: code scan
      os: linux
      dist: xenial
      sudo: required
      go: 1.12.x
      script:
        - go get -v -u github.com/alecthomas/gometalinter
        - gometalinter --install --update
        - gometalinter --vendor --tests --deadline=10m --disable-all --enable=goimports --enable=varcheck --enable=vet --enable=gofmt --enable=misspell --enable=goconst --min-occurrences=6 ./...

    # This builder run the unit tests
    - name: unit test
      os: linux
      dist: xenial
      sudo: required
      go: 1.12.x
      script:
        - go test ./...


    
