language: go
go_import_path: github.com\PlatONnetwork\PlatON-Go
# sudo: false
matrix:
  include:
    # This builder compile PlatON at Ubuntu xenial
    - stage: build
      name: ubuntu build
      os: linux
      dist: xenial
      sudo: required
      go: 1.12.x
      script:
        - chmod u+x ./build/*.sh
        - make all

    # This builder compile PlatON at Windows server 2016
    - stage: build
      name: windows build
      os: windows
      go: 1.12.x
      script:
        - chmod u+x ./build/*.sh
        - sh ./build/build_deps.sh
        - go run build/ci.go install -mpc on

    # This builder run the unit tests
    - stage: test
      name: unit test
      os: linux
      dist: xenial
      sudo: required
      go: 1.12.x
      script:
        - pwd
        - go test ./...

    # This builder run the code scans uses gometalinter
    - stage: test
      name: code scan
      os: linux
      dist: xenial
      sudo: required
      go: 1.12.x
      script:
        - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
        - golangci-lint run ./...

    
