name: unittest

on:
  pull_request:
    branches: '**'
env:
  GO111MODULE: on
jobs:
  test:
    name: Build
    runs-on: ubuntu-18.04
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: ^1.16
        id: go


      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Get dependencies
        run: |
          go get -v -t -d ./...


      - name: Build
        run: make all

      - name: Test
        run: go test -tags=test -covermode=atomic -coverprofile=coverage.txt  `go list ./...`

      - name: Upload coverage report
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
          flags: unittests
          name: codecov-umbrella

      - name: SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: -X
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
